project:
  type: website

website:
  title: "Alyssa's Personal Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: Introduction.ipynb
        text: Introduction
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



